[package]
name = "cellular_raza-template"
version = "0.1.0"
edition = "2021"
authors = ["Jonas Pleyer <jonas.pleyer@fdm.uni-freiburg.de>"]

[dependencies]
serde = "1.0.197"
rand = "0.9"
rand_chacha = "0.9"
nalgebra = "0.33"
cellular_raza = "0.2"
num = "0.4"
rayon = "1.8"
kdam = { version="0.6", features = ["template"] }
