[package]
name = "cellular_raza-template"
version = "0.1.0"
edition = "2021"
authors = ["Jonas Pleyer <jonas.pleyer@fdm.uni-freiburg.de>"]

[patch.crates-io]
nalgebra = { git = "https://github.com/dimforge/nalgebra", ref="0e8aed8809999313f0d964341e7dd83b6f1f742d" }

[dependencies]
serde = "1.0.197"
rand = "0.9"
rand_chacha = "0.9"
nalgebra = "0.33"
cellular_raza = "0.2"
num = "0.4"
rayon = "1.8"
kdam = { version="0.6", features = ["template"] }
